import { pivots } from "./pivots";

export const farms = [
  {
    farm_id: "1",
    user_id: "1",
    farm_name: "Santa Rita",
    farm_city: "Santa Rita do Sapucaí",
    farm_lng: -20.4333,
    farm_lat: -46.677,
    pivots: pivots,
  },
  {
    farm_id: "2",
    user_id: "2",
    farm_name: "Inatel",
    farm_city: "Santa Rita do Sapucaí",
    farm_lng: -20.4333,
    farm_lat: -46.677,
    pivots: pivots,
  },
  {
    farm_id: "3",
    user_id: "3",
    farm_name: "São Paulo",
    farm_city: "São Paulo",
    farm_lng: -21.4333,
    farm_lat: -46.277,
    pivots: pivots,
  },
  {
    farm_id: "4",
    user_id: "4",
    farm_name: "Santa Rita",
    farm_city: "Santa Rita do Sapucaí",
    farm_lng: -20.4333,
    farm_lat: -46.677,
    pivots: pivots,
  },
  {
    farm_id: "5",
    user_id: "5",
    farm_name: "Inatel",
    farm_city: "Santa Rita do Sapucaí",
    farm_lng: -20.4333,
    farm_lat: -46.677,
    pivots: pivots,
  },
  {
    farm_id: "6",
    user_id: "6",
    farm_name: "São Paulo",
    farm_city: "São Paulo",
    farm_lng: -21.4333,
    farm_lat: -46.277,
    pivots: pivots,
  },
  {
    farm_id: "7",
    user_id: "7",
    farm_name: "Santa Rita",
    farm_city: "Santa Rita do Sapucaí",
    farm_lng: -20.4333,
    farm_lat: -46.677,
    pivots: pivots,
  },
  {
    farm_id: "8",
    user_id: "8",
    farm_name: "Inatel",
    farm_city: "Santa Rita do Sapucaí",
    farm_lng: -20.4333,
    farm_lat: -46.677,
    pivots: pivots,
  },
  {
    farm_id: "9",
    user_id: "9",
    farm_name: "São Paulo",
    farm_city: "São Paulo",
    farm_lng: -21.4333,
    farm_lat: -46.277,
    pivots: null,
  },
];
