version: "3.8"

services:
  soil_postgres:
    image: postgres:alpine
    container_name: soil_db
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=soil
      - POSTGRES_PASSWORD=soil2021
      - POSTGRES_DB=soildb
    volumes:
      - ./backend/scripts:/docker-entrypoint-initdb.d

  soil_backend:
    build: ./backend
    container_name: soil_backend
    restart: always
    environment:
      - DATABASE_URL="mysql://soil:password@localhost:3306/newsoildb"
      - TOKEN_SECRET=suadighui3gui4gb32ui4g23u4g23
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - ./backend:/usr/soil/backend
    links:
      - soil_postgres
    depends_on:
      - soil_postgres

  soil_frontend:
    build: ./frontend
    container_name: soil_frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/soil/frontend
    links:
      - soil_backend
    depends_on:
      - soil_backend
